---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

# Data Quality Control Using R

This repository contains the supplementary materials for the presentation given to the Santa Barbara R Users community. The event took place on June 16th from 1-2pm PDT (MeetUp link [here](https://www.meetup.com/Santa-Barbara-R-Users-Group/events/286355404/?utm_medium=email&utm_source=braze_canvas&utm_campaign=mmrk_alleng_event_announcement_prod_v6_en&utm_term=promo&utm_content=lp_meetup)).

While the code in this repository is meant to be relatively self-explanatory, we do have slides (in GoogleSlides format) that were presented in addition (see [here](https://docs.google.com/presentation/d/1uYX45wOeZg5vfbjecR9-JWbthwxdEEbbLV3XVXztIF8/edit#slide=id.p))

## Supplemental Resources

- [7 Basic Quality Tools with R](https://towardsdatascience.com/7-basic-tools-of-quality-using-r-49fef5481e07)
- [Quantity is Nothing without Quality: Automated QA/QC for Streaming Environmental Sensor Data](https://academic.oup.com/bioscience/article/63/7/574/289294)
- [Implementation of a Data Management Quality Management Framework at the Marine Institute, Ireland](https://link.springer.com/article/10.1007/s12145-019-00432-w)
- [Slow improvement to the archiving quality of open datasets shared by researchers in ecology and evolution](https://ecoevorxiv.org/d63js/)
